name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ead2fb56abea8906bd44f0be3a608051c9fbbebff6c40913fadc1bde54c324f4"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
