name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f156bb12c9036921600bc0a270a305e24490f8d7be1384535e5e7bfdadc5bdf"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
