name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9845cf8442a71d869b799918f318d486c413d4986c39edc176744d122fdf2e73"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
