name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "924a3a9fcc9b0d115f36add20f65f884530456a1c5890af11945e3079ae48455"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
