name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c2d294a0fbc10a183d20f1c76f9119f46f44c0359a1516c4ce6d0c30f0fd0b7"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
