name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e94ba8fef13dccbed80fa46c3963228ab2b72a83b1cf56e567532029c6528842"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
