name = "monstro"
author = "felipao"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e75ccb9b93704b9c251c8b9d81a6b80da7efc63439e0d04f307e3e590537504"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"
